spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/clevertec_db
    username: postgres
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        show_sql: true
        format_sql: true

check:
  address: 12, MILKYWAY Galaxy / Earth
  card: card
  count: count
  discount: 0.9
  encoding: UTF-8
  id: id
  oneHundred: 100
  pageSizeDefault: 20
  pageDefault: 0
  pathPdfCheck: src/main/resources/doc/check.pdf
  pathTxtCheck: src/main/resources/doc/check.txt
  pathFont: src/main/resources/font/FreeSans.ttf
  phone: "Tel: 123-456-7890"
  quantityDiscount: 5
  supermarketName: SUPERMARKET 123
  sale: sale
  tableWidth: 300

logging:
  file:
    path: src/main/resources/log
