spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/clevertec_db
    username: postgres
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        show_sql: true
        format_sql: true

check:
  pageSizeDefault: 20
  pageDefault: 0
  id: id
  count: count
  card: card
  pathCheck: src/main/resources/doc/check.pdf

logging:
  file:
    path: src/main/resources/log
